name: Health check

on:
  push:
    branches:
      - master

jobs:
  healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Check that the app is responding
        uses: jtalk/url-health-check-action@v2
        with:
          - url: https://aqueous-plains-05063.herokuapp.com/health
