name: Health check

on:
  schedule:
    - cron: '3,18,33,48 * * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Check that the app is responding
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://aqueous-plains-05063.herokuapp.com/health
