name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello
        run: echo "Hello World!"
      - name: Current date
        run: date
      - name: Working directory contents
        run: ls -l
