name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: deploy to heroku
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: aqueous-plains-05063
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: https://aqueous-plains-05063.herokuapp.com/health
          rollbackonhealthcheckfailed: true
      - name: report successful deployment to slack
        if: always() && job.status == 'success' && github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip')
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,took
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `Successfully built and deployed ${process.env.AS_COMMIT} of ${process.env.AS_REPO} in ${process.env.AS_TOOK}`
              }]
            }
        env:
          SLACK_WEBHOOK_URL = ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: report failed build to slack
        if: always() && job.status == 'failure'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,took
        env:
          SLACK_WEBHOOK_URL = ${{ secrets.SLACK_WEBHOOK_URL }}
